/**
 * Production Environment Configuration
 * This file is auto-generated from Vercel environment variables at build time.
 * 
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten during build.
 * 
 * Environment variables are injected from Vercel:
 * - SUPABASE_URL or NEXT_PUBLIC_SUPABASE_URL
 * - SUPABASE_ANON_KEY or NEXT_PUBLIC_SUPABASE_ANON_KEY
 * - SYNCFUSION_LICENSE_KEY (optional)
 */
export const environment = {
  production: true,
  version: '0.0.1',
  supabase: {
    url: 'https://cwvkrkiejntyexfxzxpx.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3dmtya2llam50eWV4Znh6eHB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5Nzc5NDksImV4cCI6MjA3NTU1Mzk0OX0.mTYN5JRhJDrs1XUblMnUJzVVp0rUR-j9mKiX62b-Kbs'
  },
  syncfusion: {
    licenseKey: 'Ngo9BigBOggjHTQxAR8/V1JFaF5cXGRCf1FpRmJGdld5fUVHYVZUTXxaS00DNHVRdkdmWH5ccnVRQmddU0R0VkNWYEg='
  }
};
