/**
 * Environment Variable Injection Script
 * 
 * This script reads environment variables from process.env (provided by Vercel)
 * and injects them into the Angular environment files at build time.
 * 
 * Vercel provides these environment variables:
 * - SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL)
 * - SUPABASE_ANON_KEY (or NEXT_PUBLIC_SUPABASE_ANON_KEY)
 */

const fs = require('fs');
const path = require('path');

// Get environment variables from process.env
// Vercel may use different naming conventions, so we check multiple possibilities
const supabaseUrl = process.env.SUPABASE_URL || 
                    process.env.NEXT_PUBLIC_SUPABASE_URL ||
                    process.env.VERCEL_SUPABASE_URL ||
                    'https://cwvkrkiejntyexfxzxpx.supabase.co'; // Fallback for local dev

const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || 
                        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
                        process.env.VERCEL_SUPABASE_ANON_KEY ||
                        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3dmtya2llam50eWV4Znh6eHB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5Nzc5NDksImV4cCI6MjA3NTU1Mzk0OX0.mTYN5JRhJDrs1XUblMnUJzVVp0rUR-j9mKiX62b-Kbs'; // Fallback for local dev

const syncfusionLicenseKey = process.env.SYNCFUSION_LICENSE_KEY ||
                              'Ngo9BigBOggjHTQxAR8/V1JFaF5cXGRCf1FpRmJGdld5fUVHYVZUTXxaS00DNHVRdkdmWH5ccnVRQmddU0R0VkNWYEg=';

// Environment file paths
const envProdPath = path.join(__dirname, '../src/app/config/environment.prod.ts');
const envDevPath = path.join(__dirname, '../src/app/config/environment.ts');

// Template for environment.prod.ts
const prodEnvTemplate = `/**
 * Production Environment Configuration
 * This file is auto-generated from Vercel environment variables at build time.
 * 
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten during build.
 * 
 * Environment variables are injected from Vercel:
 * - SUPABASE_URL or NEXT_PUBLIC_SUPABASE_URL
 * - SUPABASE_ANON_KEY or NEXT_PUBLIC_SUPABASE_ANON_KEY
 * - SYNCFUSION_LICENSE_KEY (optional)
 */
export const environment = {
  production: true,
  version: '0.0.1',
  supabase: {
    url: '${supabaseUrl}',
    anonKey: '${supabaseAnonKey}'
  },
  syncfusion: {
    licenseKey: '${syncfusionLicenseKey}'
  }
};
`;

// For development, we can optionally update it too, or keep it as-is for local dev
// For now, we'll only update production

console.log('🔧 Injecting environment variables...');
console.log('   SUPABASE_URL:', supabaseUrl ? `${supabaseUrl.substring(0, 30)}...` : 'NOT SET');
console.log('   SUPABASE_ANON_KEY:', supabaseAnonKey ? 'SET' : 'NOT SET');
console.log('   SYNCFUSION_LICENSE_KEY:', syncfusionLicenseKey ? 'SET' : 'NOT SET');

// Write production environment file
try {
  fs.writeFileSync(envProdPath, prodEnvTemplate, 'utf8');
  console.log('✅ Updated:', envProdPath);
} catch (error) {
  console.error('❌ Error writing environment file:', error);
  process.exit(1);
}

console.log('✅ Environment variables injected successfully!');

